# (C) Copyright IBM Corporation 2016.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04-chef-12.16
    provisioner:
      require_chef_omnibus: 12.16
    driver:
      box: bento/ubuntu-14.04
  # We declare support for Chef 12.6+
  - name: ubuntu-14.04-chef-12.6.0
    provisioner:
      require_chef_omnibus: 12.6
    driver:
      box: bento/ubuntu-14.04

suites:
  - name: goodpath
    attributes:
      ibm_mq_test:
        # You need to set up a web server with the MQ packages on for the
        # tests to use, and reference the full URI as an environment variable.
        source: "<%= ENV['MQ_URI'] %>"
        queue_manager:
          name: qm1
    run_list:
      - recipe[apt::default]
      - recipe[ibm_mq_test::install]
