language: ruby

before_install:
  - wget https://packages.chef.io/stable/ubuntu/12.04/chefdk_1.0.3-1_amd64.deb -O /tmp/chefdk.deb
  - sudo dpkg -i /tmp/chefdk.deb

script:
  - chef exec rubocop
  - chef exec foodcritic .
